server:
  port: 2000

# 主数据源配置
# spring.datasource.type=com.zaxxer.hikari.HikariDataSource

spring:
  application:
    name: sea-ad-sso-server
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      max-lifetime: 1765000
      # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 15
      connection-test-query: SELECT 1

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10     # 心跳间隔（秒），默认30s
    leaseExpirationDurationInSeconds: 30  # 失效时间，默认90s，如果服务在指定的 失效时间 内仍没有发起心跳请求，将会被剔除EurekaServer
    prefer-ip-address: true               # 实例名称显示IP配置（与instance-id配合使用）
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  # 将InstanceID设置为 IP:Port 形式
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka
    healthcheck:
      enabled: true